<?php

return [
    'catalog' => [
        [
            'key' => 'ac-service',
            'name' => 'AC Service',
            'headline' => 'AC Service Operations',
            'description' => 'Kelola data masjid, unit AC, monitoring servis, SPK, dan invoice dalam satu modul operasional.',
            'tag' => 'Live',
            'badge' => 'Utama',
            'badge_variant' => null,
            'route' => 'modules.ac-service.index',
            'path' => '/modules/ac-service',
            'subdomain' => env('AC_SERVICE_DOMAIN'),
            'icon' => 'fas fa-snowflake',
            'thumb_background' => 'linear-gradient(135deg, #e8f0fe 0%, #c5d9ff 100%)',
            'thumb_color' => '#1a73e8',
        ],
        [
            'key' => 'ac-masjid-musholla',
            'name' => 'AC Masjid & Musholla',
            'headline' => 'Layanan AC Masjid & Musholla',
            'description' => 'Informasi layanan, harga, dashboard, dan monitoring unit untuk masjid dan musholla.',
            'tag' => 'Live',
            'badge' => 'Publik',
            'badge_variant' => 'catalog-card-badge--new',
            'route' => 'modules.ac-masjid-musholla.index',
            'path' => '/modules/ac-masjid-musholla',
            'subdomain' => env('AC_MASJID_MUSHOLLA_DOMAIN'),
            'icon' => 'fas fa-mosque',
            'thumb_background' => 'linear-gradient(135deg, #e3f2fd 0%, #bbdefb 100%)',
            'thumb_color' => '#1565c0',
        ],
        [
            'key' => 'ac-anggota',
            'name' => 'AC Anggota',
            'headline' => 'Portal AC Anggota',
            'description' => 'Dashboard dan monitoring untuk anggota dengan akses shared login ke data operasional.',
            'tag' => 'Live',
            'badge' => 'Anggota',
            'badge_variant' => null,
            'route' => 'ac-anggota.index',
            'path' => '/ac-anggota',
            'subdomain' => env('AC_ANGGOTA_DOMAIN'),
            'icon' => 'fas fa-users',
            'thumb_background' => 'linear-gradient(135deg, #e8f5e9 0%, #c8e6c9 100%)',
            'thumb_color' => '#2e7d32',
        ],
        [
            'key' => 'inventory',
            'name' => 'Inventory',
            'headline' => 'Inventory & Asset Tracking',
            'description' => 'Siapkan fondasi modul inventaris untuk stok, aset, dan pencatatan item lintas website.',
            'tag' => 'Planned',
            'badge' => 'Next',
            'badge_variant' => 'catalog-card-badge--hot',
            'route' => 'modules.inventory.index',
            'path' => '/modules/inventory',
            'subdomain' => env('INVENTORY_DOMAIN'),
            'icon' => 'fas fa-boxes-stacked',
            'thumb_background' => 'linear-gradient(135deg, #fef0cd 0%, #fdd99a 100%)',
            'thumb_color' => '#b06000',
        ],
        [
            'key' => 'future-module',
            'name' => 'Future Module',
            'headline' => 'Future Website Slot',
            'description' => 'Ruang siap pakai untuk mini-website berikutnya agar ekspansi modul tetap konsisten dan cepat.',
            'tag' => 'Ready',
            'badge' => 'Scalable',
            'badge_variant' => 'catalog-card-badge--new',
            'route' => 'modules.future-module.index',
            'path' => '/modules/future-module',
            'subdomain' => env('FUTURE_MODULE_DOMAIN'),
            'icon' => 'fas fa-layer-group',
            'thumb_background' => 'linear-gradient(135deg, #e8f5e9 0%, #a5d6a7 100%)',
            'thumb_color' => '#2e7d32',
        ],
    ],
];


