<?php

return [
    'catalog' => [
        [
            'key' => 'ac-service',
            'name' => 'AC Service',
            'headline' => 'AC Service Operations',
            'description' => 'Kelola data masjid, unit AC, monitoring servis, SPK, dan invoice dalam satu modul operasional.',
            'status' => 'live',
            'tag' => 'Live',
            'badge' => 'Operational',
            'badge_variant' => null,
            'route' => 'modules.ac-service.index',
            'dashboard_route' => 'dashboard',
            'login_redirect' => '/dashboard',
            'guest_cta' => 'Buka Hub',
            'auth_cta' => 'Buka Hub',
            'path' => '/modules/ac-service',
            'subdomain' => env('AC_SERVICE_DOMAIN'),
            'icon' => 'fas fa-snowflake',
            'thumb_background' => 'linear-gradient(135deg, #e8f0fe 0%, #c5d9ff 100%)',
            'thumb_color' => '#1a73e8',
        ],
        [
            'key' => 'ac-masjid-musholla',
            'name' => 'AC Masjid & Musholla',
            'headline' => 'Layanan AC Masjid & Musholla',
            'description' => 'Informasi layanan, harga, dashboard, dan monitoring unit untuk masjid dan musholla.',
            'status' => 'live',
            'tag' => 'Live',
            'badge' => 'Publik',
            'badge_variant' => 'catalog-card-badge--new',
            'route' => 'modules.ac-masjid-musholla.index',
            'dashboard_route' => 'modules.ac-masjid-musholla.dashboard',
            'login_redirect' => '/modules/ac-masjid-musholla/dashboard',
            'guest_cta' => 'Buka Layanan',
            'auth_cta' => 'Buka Hub',
            'path' => '/modules/ac-masjid-musholla',
            'subdomain' => env('AC_MASJID_MUSHOLLA_DOMAIN'),
            'icon' => 'fas fa-mosque',
            'thumb_background' => 'linear-gradient(135deg, #e3f2fd 0%, #bbdefb 100%)',
            'thumb_color' => '#1565c0',
        ],
        [
            'key' => 'ac-anggota',
            'name' => 'AC Anggota',
            'headline' => 'Portal AC Anggota',
            'description' => 'Dashboard dan monitoring untuk anggota dengan akses shared login ke data operasional.',
            'status' => 'live',
            'tag' => 'Live',
            'badge' => 'Anggota',
            'badge_variant' => null,
            'route' => 'modules.ac-anggota.index',
            'dashboard_route' => 'modules.ac-anggota.dashboard',
            'login_redirect' => '/modules/ac-anggota/dashboard',
            'guest_cta' => 'Buka Portal',
            'auth_cta' => 'Buka Hub',
            'path' => '/modules/ac-anggota',
            'subdomain' => null,
            'icon' => 'fas fa-users',
            'thumb_background' => 'linear-gradient(135deg, #e8f5e9 0%, #c8e6c9 100%)',
            'thumb_color' => '#2e7d32',
        ],
        [
            'key' => 'inventory',
            'name' => 'Inventory',
            'headline' => 'Inventory & Asset Tracking',
            'description' => 'Pantau stok kerja, aset servis, dan perlengkapan operasional dari satu dashboard inventaris ringan.',
            'status' => 'mvp',
            'tag' => 'MVP',
            'badge' => 'Scaffold',
            'badge_variant' => 'catalog-card-badge--new',
            'route' => 'modules.inventory.index',
            'dashboard_route' => 'modules.inventory.dashboard',
            'login_redirect' => '/modules/inventory/dashboard',
            'guest_cta' => 'Buka Modul',
            'auth_cta' => 'Buka Dashboard',
            'path' => '/modules/inventory',
            'subdomain' => env('INVENTORY_DOMAIN'),
            'icon' => 'fas fa-boxes-stacked',
            'thumb_background' => 'linear-gradient(135deg, #fef0cd 0%, #fdd99a 100%)',
            'thumb_color' => '#b06000',
        ],
        [
            'key' => 'future-module',
            'name' => 'Future Module',
            'headline' => 'Future Website Slot',
            'description' => 'Template kerja untuk modul berikutnya dengan checklist kesiapan route, auth, dan integrasi katalog.',
            'status' => 'mvp',
            'tag' => 'MVP',
            'badge' => 'Template',
            'badge_variant' => 'catalog-card-badge--new',
            'route' => 'modules.future-module.index',
            'dashboard_route' => 'modules.future-module.dashboard',
            'login_redirect' => '/modules/future-module/dashboard',
            'guest_cta' => 'Lihat Template',
            'auth_cta' => 'Buka Workspace',
            'path' => '/modules/future-module',
            'subdomain' => env('FUTURE_MODULE_DOMAIN'),
            'icon' => 'fas fa-layer-group',
            'thumb_background' => 'linear-gradient(135deg, #e8f5e9 0%, #a5d6a7 100%)',
            'thumb_color' => '#2e7d32',
        ],
    ],
];


