<?php

return [
    'catalog' => [
        [
            'key' => 'ac-service',
            'name' => 'AC Service',
            'headline' => 'AC Service Operations',
            'description' => 'Kelola data masjid, unit AC, monitoring servis, SPK, dan invoice dalam satu modul operasional.',
            'tag' => 'Live',
            'badge' => 'Utama',
            'badge_variant' => null,
            'route' => 'modules.ac-service.index',
            'path' => '/modules/ac-service',
            'subdomain' => env('AC_SERVICE_DOMAIN'),
            'icon' => 'fas fa-snowflake',
            'thumb_background' => 'linear-gradient(135deg, #e8f0fe 0%, #c5d9ff 100%)',
            'thumb_color' => '#1a73e8',
        ],
        [
            'key' => 'inventory',
            'name' => 'Inventory',
            'headline' => 'Inventory & Asset Tracking',
            'description' => 'Siapkan fondasi modul inventaris untuk stok, aset, dan pencatatan item lintas website.',
            'tag' => 'Planned',
            'badge' => 'Next',
            'badge_variant' => 'catalog-card-badge--hot',
            'route' => 'modules.inventory.index',
            'path' => '/modules/inventory',
            'subdomain' => env('INVENTORY_DOMAIN'),
            'icon' => 'fas fa-boxes-stacked',
            'thumb_background' => 'linear-gradient(135deg, #fef0cd 0%, #fdd99a 100%)',
            'thumb_color' => '#b06000',
        ],
        [
            'key' => 'future-module',
            'name' => 'Future Module',
            'headline' => 'Future Website Slot',
            'description' => 'Ruang siap pakai untuk mini-website berikutnya agar ekspansi modul tetap konsisten dan cepat.',
            'tag' => 'Ready',
            'badge' => 'Scalable',
            'badge_variant' => 'catalog-card-badge--new',
            'route' => 'modules.future-module.index',
            'path' => '/modules/future-module',
            'subdomain' => env('FUTURE_MODULE_DOMAIN'),
            'icon' => 'fas fa-layer-group',
            'thumb_background' => 'linear-gradient(135deg, #e8f5e9 0%, #a5d6a7 100%)',
            'thumb_color' => '#2e7d32',
        ],
    ],
];
